list: $/lincolnbrito/movies/models/genre/columns.yaml
modelClass: LincolnBrito\Movies\Models\Genre
title: Genres
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'lincolnbrito/movies/genres/update/:id'
