plugin:
    name: 'lincolnbrito.movies::lang.plugin.name'
    description: 'lincolnbrito.movies::lang.plugin.description'
    author: 'Lincoln Brito'
    icon: oc-icon-video-camera
    homepage: ''
navigation:
    main-menu-item:
        label: Movies
        url: lincolnbrito/movies/movies
        icon: icon-video-camera
        sideMenu:
            side-menu-item1:
                label: Movies
                url: lincolnbrito/movies/movies
                icon: icon-video-camera
            side-menu-item2:
                label: Genres
                url: lincolnbrito/movies/genres
                icon: icon-tag
            side-menu-item3:
                label: Actors
                url: lincolnbrito/movies/actors
                icon: icon-user
