plugin:
    name: 'lincolnbrito.movies::lang.plugin.name'
    description: 'lincolnbrito.movies::lang.plugin.description'
    author: 'Lincoln Brito'
    icon: oc-icon-video-camera
    homepage: ''
navigation:
    main-menu-item:
        label: Movies
        url: lincolnbrito/movies/movies
        icon: icon-video-camera
        sideMenu:
            side-menu-item:
                label: Genres
                url: lincolnbrito/movies/genres
                icon: icon-tag
